# .yarnrc.yml
cacheFolder: .yarn/cache

logFilters:
  - code: YN0086
    level: discard
  - code: YN0060
    level: discard
  # Behold YN0002 som error for at se vigtige advarsler

nodeLinker: node-modules
enableGlobalCache: true
enableConstraintsChecks: true

packageExtensions:
  "@angular-devkit/core@*":
    peerDependencies:
      "@types/ajv": "*"
      "@types/chokidar": "*"
  "@angular-devkit/schematics-cli@*":
    peerDependencies:
      "@types/chokidar": "*"
      chokidar: "*"
  "@angular-devkit/schematics@*":
    peerDependencies:
      "@types/chokidar": "*"
      chokidar: "*"
  "eslint-config-next@*":
    peerDependencies:
      next: "*"

# Denne linje specificerer stien til din vendored Yarn-version
yarnPath: .yarn/releases/yarn-4.9.1.cjs