cacheFolder: .yarn/cache

enableConstraintsChecks: true

enableGlobalCache: true

logFilters:
  - code: YN0086
    level: discard
  - code: YN0060
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@angular-devkit/core@*":
    peerDependencies:
      "@types/ajv": "*"
      "@types/chokidar": "*"
  "@angular-devkit/schematics-cli@*":
    peerDependencies:
      "@types/chokidar": "*"
      chokidar: "*"
  "@angular-devkit/schematics@*":
    peerDependencies:
      "@types/chokidar": "*"
      chokidar: "*"
  eslint-config-next@*:
    peerDependencies:
      next: "*"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
