cacheFolder: .yarn/cache

logFilters:
  - code: YN0086
    level: discard
  - code: YN0060
    level: discard
  - code: YN0002
    level: error

nodeLinker: node-modules

packageExtensions:
  "@angular-devkit/core@*":
    peerDependencies:
      "@types/ajv": "*"
      "@types/chokidar": "*"
  "@angular-devkit/schematics-cli@*":
    peerDependencies:
      "@types/chokidar": "*"
      chokidar: "*"
  "@angular-devkit/schematics@*":
    peerDependencies:
      "@types/chokidar": "*"
      chokidar: "*"
