services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://test:test@postgres:5432/mydb
    depends_on:
      - postgres
    ports:
      - "5002:5002"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5002
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data:
