services:
  postgres:
    image: postgres:15-alpine
    container_name: learninglab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: runner
    container_name: learninglab-api
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://test:test@postgres:5432/mydb
    ports:
      - "5002:5002"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: runner
    container_name: learninglab-web
    depends_on:
      - api
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://api:5002
    ports:
      - "3000:3000"

  reverse-proxy:
    image: nginx:latest
    container_name: learninglab-nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data: