version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: learninglab-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: learninglab-api
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/mydb
    depends_on:
      - postgres
    ports:
      - "5002:5002"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: learninglab-web
    environment:
      NEXT_PUBLIC_API_URL: http://api:5002
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data:
