services:
  postgres:
    image: postgres:15
    container_name: learninglab-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: learninglab-api:latest
    container_name: learninglab-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "5002:5002"
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: learninglab-web:latest
    container_name: learninglab-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://api:5002
    ports:
      - "3000:3000"
    depends_on:
      - api

  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    restart: unless-stopped
    depends_on:
      - api
      - web
    ports:
      - "80:80"
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data: