# Base image
FROM node:22-alpine AS base

# Set working directory
WORKDIR /app

# Install dependencies
FROM base AS dependencies
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps/web/package.json ./apps/web/package.json
COPY packages ./packages

# Install dependencies
RUN yarn install

# Build the application
FROM dependencies AS build
COPY . .
RUN yarn workspace web build

# Production image
FROM base AS production

# Copy the standalone output
COPY --from=build /app/apps/web/.next/standalone ./
COPY --from=build /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=build /app/apps/web/public ./apps/web/public

# Expose port
EXPOSE 3001

# Start the application
CMD ["node", "server.js"]