# render.yaml – placer i roden af dit monorepo
services:
  - type: web
    name: api-service
    env: node
    nodeVersion: "22"
    rootDir: apps/api
    plan: free
    region: frankfurt

    buildCommand: |
      corepack enable
      yarn install --immutable
      yarn workspace api prisma generate
      # Bygger api *og alle dens dependencies* (@repo/core, @repo/config)
      yarn turbo run build --filter=...api

    startCommand: node dist/main.js

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

    postDeployScript: yarn workspace api prisma migrate deploy
    healthCheckPath: /api
    # autoDeploy: true   # aktivér hvis du vil have auto-deploy

databases:
  - name: learning-db
    plan: free
    region: frankfurt
    ipAllowList: []
    postgresMajorVersion: "15"
