services:
  - type: web
    name: api-service
    env: node
    rootDir: apps/api
    plan: free
    region: frankfurt

    buildCommand: |
      corepack enable
      yarn install --immutable
      yarn workspace api prisma generate
      # 🚀 Bygger core, config og api i den korrekte rækkefølge
      yarn turbo run build --filter=...api
      # 🗄 Kør migrationer som en del af build
      yarn workspace api prisma migrate deploy

    startCommand: node dist/main.js
    healthCheckPath: /api
    autoDeploy: true

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: NODE_ENV
        value: production

databases:
  - name: learning-db
    plan: free
    region: frankfurt
    ipAllowList: []
    postgresMajorVersion: "15"
