services:
  - type: web
    name: api-service
    env: node
    nodeVersion: "22"
    rootDir: apps/api
    plan: free
    region: frankfurt

    buildCommand: |
      corepack enable
      yarn install --immutable
      yarn workspace api prisma generate
      # 🚀 Bygger alle afhængigheder til API'en med Turborepo (inkl. core + config)
      yarn turbo run build --filter=...api

    startCommand: node dist/main.js

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: NODE_ENV
        value: production

    postDeployScript: yarn workspace api prisma migrate deploy
    healthCheckPath: /api
    autoDeploy: true

databases:
  - name: learning-db
    plan: free
    region: frankfurt
    ipAllowList: []
    postgresMajorVersion: "15"
