retrieval:
  top_k: 50
  rerank_top_k: 10
  similarity_threshold: 0.75
  strategy: "hybrid"

embedding:
  provider: "sentence-transformers"
  model_name: "all-MiniLM-L6-v2"
  vector_size: 384

query_classifier:
  enabled: true
  threshold: 0.80
  model_path: null  # Use default classifier

llm:
  provider: "ollama"
  model_name: "llama3.1:8b"
  base_url: "http://localhost:11434"
  temperature: 0.7
  max_tokens: 1500

indexing:
  chunk_size: 500
  chunk_overlap: 50
  ignored_dirs:
    - "node_modules"
    - "dist"
    - "build"
    - ".git"
    - ".turbo"
    - ".yarn"
    - "__pycache__"
    - ".next"
  supported_extensions:
    - ".py"
    - ".js"
    - ".jsx"
    - ".ts"
    - ".tsx"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"
  file_path: "logs/rag_server.log"