global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # MCP Enterprise Server
  - job_name: "mcp-server"
    static_configs:
      - targets: ["mcp-server:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ["prometheus"]

  # Redis monitoring
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # Docker container metrics (if node_exporter is added)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    honor_labels: true

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
