
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rag_mcp_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "localhost:9093"

scrape_configs:
  - job_name: 'rag-mcp-enterprise'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['localhost:9400']  # nvidia-dcgm-exporter
    scrape_interval: 30s
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s
