name: Load Tests

on:
  workflow_dispatch:

jobs:
  locust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Locust
        run: pip install locust
      - name: Run Load Tests
        run: locust -f gcp-migration/load_tests/locustfile.py --headless -u 1 -r 1 -t1m
